name: Publish Nugets

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish Weasel.Core
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/Weasel.Core/Weasel.Core.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish Weasel.Postgresql
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/Weasel.Postgresql/Weasel.Postgresql.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish Weasel.SqlServer
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/Weasel.SqlServer/Weasel.SqlServer.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
